# Generated by Django 2.2.5 on 2019-10-09 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoikusho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('gcs', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
    ]
