# Generated by Django 2.2.5 on 2019-10-27 23:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('dam_name', models.CharField(max_length=50)),
                ('dam_code', models.IntegerField()),
                ('water_system_name', models.CharField(max_length=50)),
                ('river_name', models.CharField(max_length=50)),
                ('type_code', models.CharField(max_length=20)),
                ('purpose_code', models.CharField(max_length=20)),
                ('scale_bank_height', models.FloatField()),
                ('scale_bank_span', models.FloatField()),
                ('bank_volume', models.IntegerField()),
                ('total_pondage', models.IntegerField()),
                ('institution_in_charge', models.CharField(max_length=20)),
                ('year_of_completion', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('positional_information_precision', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4019)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.Category', verbose_name='カテゴリ')),
            ],
            options={
                'db_table': 'infra',
                'abstract': False,
            },
        ),
    ]
