# Generated by Django 2.2.5 on 2019-11-08 06:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('address', models.CharField(max_length=60, verbose_name='住所')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='カテゴリ')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('dam_code', models.IntegerField()),
                ('water_system_name', models.CharField(max_length=50)),
                ('river_name', models.CharField(max_length=50)),
                ('scale_bank_height', models.FloatField()),
                ('scale_bank_span', models.FloatField()),
                ('bank_volume', models.IntegerField()),
                ('total_pondage', models.IntegerField()),
                ('year_of_completion', models.CharField(max_length=10)),
                ('positional_information_precision', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4019)),
                ('institution_in_charge', models.ManyToManyField(blank=True, null=True, to='dam.Institution')),
                ('purpose_code', models.ManyToManyField(blank=True, null=True, to='dam.Purpose')),
                ('type_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dam.DamType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
