# Generated by Django 2.2.5 on 2019-11-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dam',
            name='dam_name',
        ),
        migrations.AlterField(
            model_name='dam',
            name='address',
            field=models.CharField(max_length=50, verbose_name='住所'),
        ),
    ]
