# Generated by Django 2.2.5 on 2019-11-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0002_auto_20191106_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dam',
            table='dam',
        ),
    ]
