# Generated by Django 2.1.11 on 2020-01-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cloudinary_url', models.URLField(blank=True, null=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dam.Dam')),
            ],
        ),
    ]
