# Generated by Django 2.2 on 2020-01-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dam.Dam'),
        ),
    ]
