from django.contrib.gis.db import models

class Dam(models.Model):
    dam_name = models.CharField(max_length=50)
    dam_code = models.IntegerField()
    water_system_name = models.CharField(max_length=50)
    river_name = models.CharField(max_length=50)
    type_code = models.CharField(max_length=20)
    purpose_code = models.CharField(max_length=20)
    scale_bank_height = models.FloatField()
    scale_bank_span = models.FloatField()
    bank_volume = models.IntegerField()
    total_pondage = models.IntegerField()
    institution_in_charge = models.CharField(max_length=20)
    year_of_completion = models.CharField(max_length=10)
    address = models.CharField(max_length=250)
    positional_information_precision = models.IntegerField()
    geom = models.PointField(srid=4019)

    # w01_001 = models.CharField(max_length=0)
    # w01_002 = models.IntegerField()
    # w01_003 = models.CharField(max_length=0)
    # w01_004 = models.CharField(max_length=0)
    # w01_005 = models.CharField(max_length=0)
    # w01_006 = models.CharField(max_length=0)
    # w01_007 = models.FloatField()
    # w01_008 = models.FloatField()
    # w01_009 = models.IntegerField()
    # w01_010 = models.IntegerField()
    # w01_011 = models.CharField(max_length=0)
    # w01_012 = models.CharField(max_length=0)
    # w01_013 = models.CharField(max_length=0)
    # w01_014 = models.IntegerField()
    # geom = models.PointField(srid=4019)
