# Generated by Django 2.2.6 on 2019-10-26 15:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damName', models.CharField(max_length=255)),
                ('damCode', models.IntegerField()),
                ('waterSystemName', models.CharField(max_length=255)),
                ('riverName', models.CharField(max_length=255)),
                ('dam_type', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('damScaleBankHeight', models.FloatField()),
                ('damScaleBankSpan', models.FloatField()),
                ('bankVolume', models.IntegerField()),
                ('totalPondage', models.IntegerField()),
                ('institutionInCharge', models.CharField(max_length=255)),
                ('yearOfCompletion', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('positionalInformationPrecision', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
    ]
